version: '3'

services:
  todoback:
    image: todobackend
    restart: always
    networks:
      - lan1
    ports:
      - '3001:3001'

  todofront:
    image: todofrontend
    restart: always
    networks:
      - lan1
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback

  todotests:
    image: todotests
    restart: always
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
    networks:
      - lan1

networks:
  lan1:
